-- Sample global prompt and context for local development
insert into public.prompts (id, name, description, system_prompt)
values (
  '00000000-0000-0000-0000-000000000001',
  'Daily Momentum Coach',
  'Guides the user through planning, reflection, and goal alignment while driving or walking.',
  $$You are a calm, proactive voice coach that helps the user align their intentions for the day, reflect on progress, and create space to think.$$)
on conflict (id) do update
set name = excluded.name,
    description = excluded.description,
    system_prompt = excluded.system_prompt,
    updated_at = timezone('utc', now());

insert into public.prompt_contexts (id, prompt_id, name, description, context_payload, aux_schema_required)
values
  (
    '00000000-0000-0000-0000-000000000101',
    '00000000-0000-0000-0000-000000000001',
    'Daily Goals Snapshot',
    'Summaries of the active goals and their latest progress.',
    jsonb_build_object('source', 'user_goals', 'fields', array['title', 'status', 'goal_state']),
    false
  ),
  (
    '00000000-0000-0000-0000-000000000102',
    '00000000-0000-0000-0000-000000000001',
    'Recent Insights',
    'Highlights generated by background jobs to prompt reflection.',
    jsonb_build_object('source', 'insights', 'limit', 5),
    false
  ),
  (
    '00000000-0000-0000-0000-000000000103',
    '00000000-0000-0000-0000-000000000001',
    'Trend Markers',
    'Aggregated streaks and daily usage markers to reinforce habit formation.',
    jsonb_build_object('source', 'trends', 'metrics', array['daily_check_ins', 'streak_days']),
    false
  )
on conflict (id) do update
set name = excluded.name,
    description = excluded.description,
    context_payload = excluded.context_payload,
    aux_schema_required = excluded.aux_schema_required,
    updated_at = timezone('utc', now());

-- Auxiliary metadata example for reference
insert into public.context_aux_tables (id, prompt_context_id, table_name, ddl)
values (
  '00000000-0000-0000-0000-000000000201',
  '00000000-0000-0000-0000-000000000101',
  'goal_journal_entries',
  $$create table if not exists public.goal_journal_entries (
    id uuid primary key default gen_random_uuid(),
    session_uuid uuid references public.sessions(session_uuid) on delete cascade,
    goal_id uuid references public.user_goals(id) on delete cascade,
    note text not null,
    created_at timestamptz not null default timezone('utc', now())
  );$$
)
on conflict (id) do update
set table_name = excluded.table_name,
    ddl = excluded.ddl,
    prompt_context_id = excluded.prompt_context_id;

